### ISSUE TITLE
dispatch_queue_t is unavailable in Swift ，did you update cocoaPods ?

### ISSUE THREAD

**Issue by liamscofield** [duemunk/Async#102]
I used cocoapods AsyncSwift 1.7.3 but it tips that many error of not compatible with swift3.0

**Comment by duemunk** [comment]
It's live :) Thanks for helping out!

**Comment by RoRoche** [comment]
I'm still having this issue, what's the solution?

**Comment by duemunk** [comment]
@RoRoche Have you alleviated the issue?

**Comment by RoRoche** [comment]
Yes it's now alright. Thanks
