### ISSUE TITLE
ITMS-90056 This bundle is invalid. The Info.plist file is missing the required key: CFBundleVersion

### ISSUE THREAD

**Issue by toshi0383** [duemunk/Async#106]
I had a iTC upload issue.

iOS app
Integrated with Carthage

CFBundleVersion of Async was actually empty.
I think it's better to set CFBundleVersion to whatever value like `1.0`.

**Comment by duemunk** [comment]
Have you been able to solve it by setting CFBundleVersion? If so, feel free to create a pull request?

**Comment by itaydressler** [comment]
Getting the same issue.

**Comment by toshi0383** [comment]
I'm working on it.

**Comment by aral** [comment]
Hey there, any word on merging the pull request for this? Having the same issue (app failing App Store submission due to this when built with Carthage).

**Comment by duemunk** [comment]
The PR was a bit big and worked on continuously, so forgot about it. I've continued the discussion on the PR :)

**Comment by aral** [comment]
@duemunk I figured as much when I saw it and thought I’d give it a little bump ;) Thanks for jumping in so quicky (PS. I’ve updated the one library and app itself to use @toshi0383’s branch for now; will revert to master once it’s in.)
