### ISSUE TITLE
CompileSwift normal arm64

### ISSUE THREAD

**Issue by lethianqt94** [duemunk/Async#107]
*\* BUILD FAILED **
321
    The following build commands failed:
322
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
323
        CompileSwift normal arm64 /tmp/sandbox/workspace/Pods/AsyncSwift/Source/Async.swift
324
    (2 failures)

 I converted my current project to Swift 3. Then built new project with BuddyBuild. I got this error. Any solutions?

**Comment by qi-shun-wang** [comment]
** BUILD FAILED **
68
    The following build commands failed:
69
    	CompileSwift normal arm64 /tmp/sandbox/workspace/MOXS/Kingfisher/ImageCache.swift
70
    	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
71
    (2 failures)


I got the same problems.please help!

**Comment by duemunk** [comment]
Please re-open if this issue is still valid.

**Comment by godeepti** [comment]
I see the exact same build error when try to build from terminal
xcodebuild build-for-testing -scheme <Scheme>

**Comment by sharephoenix** [comment]
Please re-open if this issue is still valid. or tell me the answer of issue
Xcode 11.4
Build version 11E146
