### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Ponyboy47** [duemunk/Async#111]
Async cannot work without Dispatch being imported on it, also, some of the qos features don't work on linux as well

**Comment by Ponyboy47** [comment]
Anyone who runs into issues with this supporting linux should check out my fork. It compiles/runs on linux and has a few additional features that I felt were missing, such as Synchronous support as well. And my code is organized a little better (multiple small files instead of one massive file)

https://github.com/Ponyboy47/Async

**Comment by duemunk** [comment]
Why didn't you make a pull request for this repo?

**Comment by Ponyboy47** [comment]
In my fork I removed Carthage and Cocoapods junk since I wasn't using any of it and I don't want to create a pull request here since that would remove that support here as well

**Comment by Ponyboy47** [comment]
I could make one if you'd like for me to just so you could see everything I did? Functionality is still the same despite all that I've done. I really just didn't want to squash Carthage/Cocoapods
