### ISSUE TITLE
iOS deployment target issue

### ISSUE THREAD

**Issue by tylerlong** [duemunk/Async#118]
Please refer to https://github.com/Carthage/Carthage/issues/1951

> Looks like the library does support iOS 8 in its podspec: https://github.com/duemunk/Async/blob/2.0.3/AsyncSwift.podspec#L10 but the generated Xcode project by swift package generate-xcodeproj does not. So please file an issue on that repository.

**Comment by duemunk** [comment]
Is it related to #121?
