### ISSUE TITLE
AsyncSwift.podspec is outdated

### ISSUE THREAD

**Issue by vldalx** [duemunk/Async#124]
When I try to install that framework using `CocoaPods` then `2.0.1 version` will be installed. Any particular version is not specified in my Podfile.
Furthermore, the latest version should contain the recent changes related to Swift 4 support.

**Comment by duemunk** [comment]
I'm getting this error when trying to push to pod trunk:
```
** BUILD SUCCEEDED **

   Testing with xcodebuild. 
 -> AsyncSwift (2.0.4)
    - ERROR | file patterns: The `source_files` pattern did not match any file.
```

**Comment by vldalx** [comment]
I've created [RP](https://github.com/duemunk/Async/pull/126) for this issue

**Comment by duemunk** [comment]
New error:
```
The following build commands failed:
	Check dependencies
(1 failure)
   Testing with xcodebuild. 
 -> AsyncSwift (2.0.4)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.

[!] The spec did not pass validation, due to 1 error.
```

**Comment by vldalx** [comment]
because `testAfterGCD` is failed. But the test's code looks fine.

**Comment by vldalx** [comment]
fix for the test is [here](https://github.com/duemunk/Async/pull/127)

**Comment by vldalx** [comment]
@duemunk  please remove 2.0.4 tag from the old commit and add to the new one

**Comment by rlam3** [comment]
I don't see any pod updates either. Is there something wrong on cocoapods end?

**Comment by vldalx** [comment]
@duemunk let's finish what we started.
I fixed `testAfterGCD` test. Please, merge the [PR](https://github.com/duemunk/Async/pull/127). Then either move '2.0.4' tag to the last commit or add a new one, update podspec file

**Comment by duemunk** [comment]
Another day, another CocoaPods issue:
```
=== CLEAN TARGET AsyncSwift OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET AsyncSwift OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
   Testing with xcodebuild. 
 -> AsyncSwift (2.0.4)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
```

**Comment by duemunk** [comment]
Does CocoaPods have some kind of validator you can use to check whether it would work for me to push?

**Comment by vldalx** [comment]
I run the command
`pod spec lint AsyncSwift.podspec --verbose`
AsyncSwift.podspec passed validation

Do you use [the latest cocapods' version](https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods)?

**Comment by vldalx** [comment]
By the way, you can run the command
`pod spec lint AsyncSwift.podspec --verbose --swift-version=4`
to be sure about the swift version 4 is fine on your side

**Comment by rlam3** [comment]
i had to add  :github => https://github.com/duemunk/Async.git to get it to work ....

**Comment by vldalx** [comment]
@rlam3 Did you mean `pod spec lint` command?
Could you describe exactly what you did and where?

**Comment by duemunk** [comment]
The last error was because of the build not using the correct Xcode Command Line Tool version. Things have now been pushed.
