### ISSUE TITLE
Cannot load module 'async' as 'Async'

### ISSUE THREAD

**Issue by billzt** [duemunk/Async#130]
I feel very strange when installing by Carthage.

Usually, using a Carthage framework is very easy. Just Setting: General -> Embedded Binaries and add the built frameworks like this:
<img width="587" alt="qq20180111-110627 2x" src="https://user-images.githubusercontent.com/1146090/34806734-c40415b4-f6bf-11e7-9041-060c9dcdfe09.png">

However, when I finish this and wrote:
```
import Async
```

It immediately shows an error:
```
Cannot load module 'async' as 'Async'
```
Why?

**Comment by duemunk** [comment]
Did you manage to fix the issue? Else please re-open.
