### ISSUE TITLE
Does not support iOS 12 

### ISSUE THREAD

**Issue by bertugylmaz** [duemunk/Async#132]
Released iOS 12 and always get crash report 👇🏻

Please help me and solved this issue

closure #1 () -> () in static Async.AsyncBlock.(async in _E687294E1917D2F98ED787A27C7576C6)<A>(after: Swift.Double?, block: () -> A1, queue: Async.(GCD in _E687294E1917D2F98ED787A27C7576C6)) -> Async.AsyncBlock<(), A1>
reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> ()

**Comment by duemunk** [comment]
Fixed in #131
