### ISSUE TITLE
SPM Compatibility

### ISSUE THREAD

**Issue by colemcampbell** [duemunk/Async#140]
Is Swift Package Manager compatibility in the works? There's a Package.swift file in the repository but it doesn't seem to have ever been completed.

**Comment by colemcampbell** [comment]
Thanks for merging my branch! It currently works to pull from the master branch but it doesn't work with version rules currently because there isn't a tag that includes the updates to the package file.

**Comment by duemunk** [comment]
I've given you collaborator access. Feel free to update the version to a new one. Probably warrants a bump to 2.1.0.

**Comment by duemunk** [comment]
The readme could also benefit from adding SPM as an install method, probably the primarily suggested one.

**Comment by colemcampbell** [comment]
Do you want me to make a pull request with the necessary changes so that you can merge it and create a new tag, or would you like me to create the new tag as well?

**Comment by duemunk** [comment]
If you can all of it (including the tag) from your end I'll highly appreciate it.

**Comment by colemcampbell** [comment]
I updated the README and bumped the version number. I tested adding the package to a local project of mine and everything seems to be working!

**Comment by duemunk** [comment]
Great! 

Fixed in #143.
