### ISSUE TITLE
pass parameters through blocks

### ISSUE THREAD

**Issue by MaxenceMax** [duemunk/Async#145]
Hi guys !

I found another issue which is talking about how to pass parameters through blocks, but I didn't find the answer to do something like that 

```
func Appear(){
        Async.background {
            self.OccurrenceManager.getAllOccurrences { occs in
                // This block in main block
                self.occurrencesPublisher.send(occs.count)
            }
        }.main {
            // I want to achieve it here
        }
    }
```

**Comment by duemunk** [comment]
Async has not be created to solve indentation and nesting in your own calls. You might be able to have `getAllOccurences` return an `Async` instance. If you find a workable solution, feel free to share it here for future reference.
