### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by ksmandersen** [duemunk/Async#16]
I added a podspec to my fork of the repo https://github.com/ksmandersen/Async.

I doesn't lint yet because RC versions of CocoaPods are not publisehd via RubyGems. To use Swift cocoapods you must install CocoaPods from source http://guides.cocoapods.org/using/unreleased-features. 

I will hold off on a Pull Request support is official for swift

**Comment by duemunk** [comment]
As of the latest CocoaPods release everything works fine.
