### ISSUE TITLE
Module name conflict.

### ISSUE THREAD

**Issue by remaerd** [duemunk/Async#21]
Hello.

I like Async a lot. I fork it and try to make it support Carthage. When I try to create build targets. Interesting things happened.

The module name 'Async' is causing a ```could not build Objective-C module 'Async'``` bug. When I try other names such as SwiftAsync. It works fine.

I'm wondering what is the best choice to support Carthage... What do you think?

**Comment by duemunk** [comment]
See #23 for Carthage support
