### ISSUE TITLE
CocoaPods Trunk

### ISSUE THREAD

**Issue by nanoxd** [duemunk/Async#29]
I was wondering if you intended to push this library to Cocoapod's trunk. There is currently an `Async` library that would conflict with this one so a name change might be needed. This would allow users to use `pod 'AsyncSwift'` in their `Podfile`

[Guide to get setup on trunk](http://guides.cocoapods.org/making/getting-setup-with-trunk.html)

Thanks for the amazing work :+1:

**Comment by duemunk** [comment]
Hmm, bummer. It's kinda sad to need to change the filename to `AsyncSwift.podspec`. 

Does anyone have any ideas that does require name change?

**Comment by nanoxd** [comment]
There is a claims form for CocoaPods but that's more for libraries that were submitted by other users that the developer wants to claim. In this case maybe talking to @johnwana to change his pod instead?

**Comment by duemunk** [comment]
Yeah, no. @johnwana's repo is a pure valid use of CocoaPods. It's unfortunate that CocoaPods don't allow to push to trunk with a different name IMO.

**Comment by todaylover** [comment]
seem that the punk wasn't pushed?

**Comment by duemunk** [comment]
@todaylover ??

**Comment by todaylover** [comment]
the filename has been decided?  ah. you can make a decision

**Comment by todaylover** [comment]
the filename has been decided?  ah. you can make a decision

**Comment by danthorpe** [comment]
I expect that most developers maintain their own Spec's repo, and all that is required is to add an Async directory structure to that.

There is one issue at the moment, and that is a missing remote tag for `1.2.0` so the current podspec is not valid.

**Comment by 0angelic0** [comment]
So, How can I install this Async from CocoaPods?
I placed `pod 'Async'` in Podfile but then it installed https://github.com/johnwana/Async instead of this Async.

**Comment by danthorpe** [comment]
@0angelic0 you can great your own Specs repo, and put Async in it like this, for example: https://github.com/yakatak/Specs/tree/master/Async/1.2.0

Then add this repo to your Podfile e.g. 

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/<< your github name >>/Specs.git'

```

Then you can use:

```ruby
pod 'Async'
```

And CocoaPods will "override" the Async which is in the Master repo. If you wanted to use both, then name changes need to happen. Which is what @duemunk will probably have to do in the long run if he wants to submit Async to the trunk.

n.b. Don't use someone else personal Spec's repo - create and maintain your own.

**Comment by 0angelic0** [comment]
@danthorpe Thanks! I followed your guide and it worked.

**Comment by duemunk** [comment]
I might have misunderstood something, but why not just use `pod 'Async', :git => 'https://github.com/duemunk/Async.git'` ?

**Comment by danthorpe** [comment]
@duemunk @0angelic0 yes, this will work if you want to use `Async` in an application. But it won't work if you want to use it inside an internal framework/dependency.

**Comment by duemunk** [comment]
Ah, ok. That makes sense. I think the only solution is to call CocoaPods part of the project **AsyncSwift**.
It would be ok to keep `class Async` right?

**Comment by danthorpe** [comment]
Absolutely, the class name doesn't need to change. It's just a CocoaPods namespacing issue.

**Comment by juzzin** [comment]
Renaming the pod to AsyncSwift would be really helpful. It would allow this project to be used as a podspec dependency.

**Comment by duemunk** [comment]
I've changed the CocoaPods name to *AsyncSwift* now and pushed to the trunk. Hopefully this works.

**Comment by juzzin** [comment]
That was quick. Thanks. 👍
