### ISSUE TITLE
Cartfile

### ISSUE THREAD

**Issue by kingslay** [duemunk/Async#34]
when i use Cartfile 
github "duemunk/Async" then has an error
Project "AsyncExample.xcodeproj" has no shared schemes

**Comment by duemunk** [comment]
@mowens?

**Comment by mowens** [comment]
@duemunk which ever target builds the dynamic framework must be shared in the xcode project. If I recall the framework target wasn't merged in favor of cocoa pods? I'm currently on holiday and won't be back to my laptop til next week so I can't verify
