### ISSUE TITLE
Merge master branch into feature/Swift_2.0 for Carthage build.

### ISSUE THREAD

**Issue by inamiy** [duemunk/Async#36]
Current 23aaf8d (feature/Swift_2.0 branch) doesn't contain any xcodeproj or xcworkspace to build Async.framework, so `carthage build` will never get started.

It seems current master branch (v1.2.1) already has one, so please merge it into feature/Swift_2.0 so that I can test Swift 2 using Carthage.

**Comment by duemunk** [comment]
Fixed in a7d2aa78c9830ca1ede52fb3db69079e47c32d05. Please let me now if it works as expected.
