### ISSUE TITLE
qos_class_self() func can't get the current thread Qos class

### ISSUE THREAD

**Issue by myloveCc** [duemunk/Async#38]
when i run the test project，qos_class_self() func can't get the current thread Qos class，and then the test failed。

**Comment by duemunk** [comment]
Which test? And what branch? And what version of XCode?

**Comment by duemunk** [comment]
I can't reproduce this without any more information, so it will be closed for now.

**Comment by myloveCc** [comment]
Oh,I am test AsyncExample_iOSTests project in Xcode 6.4.

**Comment by duemunk** [comment]
Do you run it on a device as specified?

**Comment by myloveCc** [comment]
I run it on Iphone6 simulator ,but the test failed also.

**Comment by duemunk** [comment]
You should _not_ run in it in the simulator. GCD isn't simulated perfectly, so the tests only work on the device.

**Comment by myloveCc** [comment]
Oh，I see , thanks for your replay, have a nice day.
