### ISSUE TITLE
Question: is there a way to use the project within Objective-C files?

### ISSUE THREAD

**Issue by oferRounds** [duemunk/Async#39]
If I understand right, the answer is no, because Async is a struct. But I'm not sure...
Thanks for this great project!

**Comment by duemunk** [comment]
Uhm, I actually have no idea how this works in ObjC, but your probably right. I've never had a thought of "looking back" :)

Most of Async builds on trailing closures, so wouldn't make much sense in ObjC anyway. 

It's just a DSL for GCD which is C-code, so could possibly make some bridge code for ObjC compatibility.

Would you ever transfer the asynchronous chaining from Swift to ObjC? Else it wouldn't help much.

**Comment by oferRounds** [comment]
Thanks for the answer! Yes, I would - that's the trigger for the question.

**Comment by duemunk** [comment]
Could you show an example? Just a simple one between two files of either type (Swift and ObjC).

**Comment by duemunk** [comment]
Closing due to no response.
