### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by duemunk** [duemunk/Async#4]

**Comment by tciuro** [comment]
Say you have N ops which should be run in the background, then wait (“join”) when all have completed, then proceed to another one. Can we do that? For example:

	Async.background {
	    // 1: perform op A
	}.background {
	    // 2: perform op B
	}.background {
	    // 3: perform op C
	}.join(*) {
	    // 4: this block gets called when A, B and C have completed
	}
	(*)Could be join, wait, finalize, etc.

I see the example in the `“How does it work”` section (example with `“ dispatchQueueForChainingBlock”`), and I was hoping that it would be integrated with Async. More sugar, less fat ;-)

Also, it would make it easier to adopt if the documentation mentioned what every agent does. For example, you make it very clear what queue classes are supported. But the fact that `.main(after: seconds`) is allowed it’s not really mentioned. That is, there isn’t a section devoted to extra ops allowed. How about the following:

- does `.background` support `after:seconds`? (yes, it does, I know… but one has to read the entire docs looking for clues)
- what are the ops allowed in a block? I see `wait()`, `cancel()`… anything else?
- any other ops that should be mentioned?
