### ISSUE TITLE
module-includes Swift compiler warning

### ISSUE THREAD

**Issue by Leshich** [duemunk/Async#40]
Hello. Why i get these warnings and how to fix it?
![screen shot 2015-07-17 at 17 40 22](https://cloud.githubusercontent.com/assets/4246455/8747295/ff00a754-2caa-11e5-83a5-5af23a50f710.png)

**Comment by duemunk** [comment]
Please provide more information about install method and software versions. Also, did this use to work for you?

**Comment by Leshich** [comment]
Really strange, but it has disappeared itself.
I had a cocoapods swift project with bridging header.
Sorry for disturbing)
