### ISSUE TITLE
Pod install Error [Couldn't connect to server]

### ISSUE THREAD

**Issue by DaRkD0G** [duemunk/Async#42]
Hi i have this error ... 

[!] Error installing Async
[!] /usr/bin/git clone https://github.com/duemunk/Async.git /var/folders/7n/7h94xgjj3c13jc_nhr6xkbl00000gn/T/d20150802-45792-13l6qgp --single-branch --depth 1

Cloning into '/var/folders/7n/7h94xgjj3c13jc_nhr6xkbl00000gn/T/d20150802-45792-13l6qgp'...
fatal: unable to access 'https://github.com/duemunk/Async.git/': Couldn't connect to server

**Comment by duemunk** [comment]
Sooo, a Github error? Does it work now?
