### ISSUE TITLE
Question: Does Async implement Capture Lists?

### ISSUE THREAD

**Issue by ctews** [duemunk/Async#43]
Just a small question does Async honor Swift Capture Lists if you use `self` references in an Async.background closure?

**Comment by duemunk** [comment]
I don't know of Capture Lists. What are they?
Async works no different than GCD and blocks in general as far as I know. 

I usually do the [weak self] dance if necessary.

**Comment by ctews** [comment]
Ah sorry, my fault ;) dumb question I used to use the short Syntax `Async.background { ... }` but of course you can use `Async.background { [unowned/weak self]() -> Void in ... }`.

Stupid me ;)
