### ISSUE TITLE
Add Swift 2.0 Version Tag

### ISSUE THREAD

**Issue by mikenolimits** [duemunk/Async#45]
Hi,

Would it be possible to tag a release for swift 2.0, so that we can add Async as a dependency in our pods?

**Comment by duemunk** [comment]
I'm actually not quite sure how to do this. Also, my likeness for CocoaPods is beginning to decrease, do to all this maintenance work :)

**Comment by mikenolimits** [comment]
` git checkout feature/swift2.0` 
`git  tag 1.4` 
`git add . && git commit -m "swift 2.0 tag" && git push` 

Should work ?

**Comment by duemunk** [comment]
I've pushed a tag now.

**Comment by mikenolimits** [comment]
I think the s.version in the podspec also needs to be updated to 1.4

No problem!
