### ISSUE TITLE
merge swift 2.0 into master

### ISSUE THREAD

**Issue by mikenolimits** [duemunk/Async#50]
xCode 7 is out so maybe this is the right time :)?

**Comment by Leshich** [comment]
+

**Comment by duemunk** [comment]
There are som open issues with Xcode 7 and Async that needs to be sorted out first, i.e. #46.

**Comment by christianlanz** [comment]
+1

**Comment by efremidze** [comment]
+1

**Comment by zixun** [comment]
+1

**Comment by funky-monkey** [comment]
+1

**Comment by joslinm** [comment]
:+1:

**Comment by duemunk** [comment]
I'm not going to merge. See #46 for why. Next merge to `master` will be from a Swift 2.1 branch.
