### ISSUE TITLE
This doesn't work at all via cocoa pods

### ISSUE THREAD

**Issue by barrettj** [duemunk/Async#55]
The pod spec is saying source files are in the Sources directory but they aren't, they're in a Async.swift in the root.

This results in a pod being adding with no source files and no functionality.

**Comment by bclymer** [comment]
Can confirm that happened since the swift 2.1 merge :(

**Comment by duemunk** [comment]
Sorry. Was in a bit of a hurry when merging 2.1 in :/ 

It should have been fixed now!

**Comment by bclymer** [comment]
@duemunk it looks like you moved the swift 1.2 code into sources

https://github.com/duemunk/Async/blob/master/Source/Async.swift#L119

the `#` is no longer valid.

**Comment by heyalexchoi** [comment]
:+1:

**Comment by duemunk** [comment]
Oh no. Impeccable me :)

I've just fixed it. Tested on OS X and iOS Simulator. If there's is more related to this issue, please feel free to reopen. 

I'm going to bed now :)
