### ISSUE TITLE
Travis CI not running tests

### ISSUE THREAD

**Issue by duemunk** [duemunk/Async#57]
I can't make Travis CI work (spoiler: I haven't used it before). Check it our [here](http://travis-ci.org/duemunk/Async).

For every single test, the log states:
```
Test did not run: the test bundle stopped running or crashed before the test suite started.
```
The tests are only run for the OS X target.

**Comment by kostiakoval** [comment]
Do you need to update `xctool` ? and use `   - LANG=en_US.UTF-8` setting. 
I think it could be deleted. as a first step

```
env:
   global:
   - LANG=en_US.UTF-8


before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
```

**Comment by kostiakoval** [comment]
try removing sdks and clean

.travis file 
```
osx_image: xcode7.1

language: objective-c

- xctool build -project Async.xcodeproj -scheme "Async iOS"
- xctool build -project Async.xcodeproj -scheme "Async OSX"
- xctool  build test -project AsyncTest/Async.xcodeproj -scheme "AsyncOSX"

after_success:
- bash <(curl -s https://codecov.io/bash)
```

**Comment by kostiakoval** [comment]
Here is a problem. When I run this command on my local PC, it crashes

`- xctool  build test -project AsyncTest/Async.xcodeproj -scheme "AsyncOSX"`

Probably it's the same bug on travis
```
Test did not run: the test bundle stopped running or crashed before the test suite started.

application requires at least Mac OS X version 10.11.0 (10.11), but is being run on 10.10.5 ( 10.10.5/14F1021), and so is exiting.
CRASH REPORT: AsyncOSX_2015-11-03-213633_Konstantins-MacBook-Pro.crash

Process:               AsyncOSX [83287]
Path:                  /Users/USER/*/AsyncOSX.app/Contents/MacOS/AsyncOSX
Identifier:            AsyncOSX
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        xctool [82726]
Responsible:           iTerm [227]
User ID:               501

Date/Time:             2015-11-03 21:36:31.949 +0100
OS Version:            Mac OS X 10.10.5 (14F1021)
....
```

**Comment by kostiakoval** [comment]
When I open project and try to run tests they are failing.
Unit test should be ruined very fast, it it takes more that 0,5 second to run a test - it's way to much

![screen shot 2015-11-03 at 21 49 09](https://cloud.githubusercontent.com/assets/1086260/10921279/eba875ae-8274-11e5-90f5-d55a4a9fe3bb.png)

**Comment by duemunk** [comment]
I copied some else `.travis.yml`, so most things aren't because I know they need to.

Whether I use `xctool locally or `xcodebuild` it works just fine.

I've changed som thing in the tests, so they're less likely to fail due to GCD acting up e.g. som "after" 1.1 second fired 1.09 seconds after. Now I have padding of time on both sides of target.

The length of the tests are to wait for testing `dispatch_async_after`. Since they respond ±200 ms, the test have target times to 1-2 seconds. Could probably reduce a bit, but then the tests would be less accurate.

**Comment by kostiakoval** [comment]
if it works local it should also work remotely. Just make sure to use OS X 10.10.5
Also here is mine very simple travis file, and it works
https://github.com/kostiakoval/PiList/blob/master/.travis.yml

**Comment by duemunk** [comment]
Travis doesn't support 10.11?

**Comment by kostiakoval** [comment]
nope :( not yet, you can see it in the log error message. 
https://travis-ci.org/duemunk/Async/builds/89083187
![screen shot 2015-11-06 at 13 21 26](https://cloud.githubusercontent.com/assets/1086260/10996935/51fbeff0-8489-11e5-8df8-456cc9fe5011.png)

application requires at least Mac OS X version 10.11.0 (10.11), but is being run on 10.10.5 ( 10.10.5/14F27), and so is exiting.

**Comment by kostiakoval** [comment]
just change the target to older OS X version. then it works

**Comment by duemunk** [comment]
Also change the SDK?

**Comment by duemunk** [comment]
Oh, that one is set to "Latest" so should work fine.

**Comment by kostiakoval** [comment]
Check my changes I did in this PR

**Comment by duemunk** [comment]
Yeah, I've included them! Thanks :+1:

**Comment by duemunk** [comment]
The tests work now!! Thanks for the help.

The iOS build fails though. Due to some code signing. Is it really necessary to set that op to make it work?

**Comment by kostiakoval** [comment]
nope I don't think so. But you need to set correct signing setting in the project

**Comment by duemunk** [comment]
Would this by any change be "correct"?

<img width="540" alt="screen shot 2015-11-06 at 15 29 53" src="https://cloud.githubusercontent.com/assets/489138/10999256/41a6cc8a-849b-11e5-9bd8-5b8b14831358.png">
