### ISSUE TITLE
Carthage Failure building tvOS

### ISSUE THREAD

**Issue by kgn** [duemunk/Async#59]
Not sure if this is an issue in Carthage, or the tvOS scheme needs to code sign the framework in the Async project.

```
*** Building scheme "Async tvOS" in Async.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
CodeSign error: code signing is required for product type 'Framework' in SDK 'tvOS 9.0'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by duemunk** [comment]
Has it ever worked with Async to tvOS with Carthage? Never tested it.

**Comment by ksmandersen** [comment]
Just tried the last couple of versions. They all fail. Not sure what the problem is here. Some project settings perhaps

**Comment by ksmandersen** [comment]
I temporary workaround for people not interested in build for tvOS is to either use the 1.4.2 version tag or to simple build only the platforms you target with ``carthage update --platform "iphoneos"``

**Comment by duemunk** [comment]
Ok. I'm looking in to it now. There was some odd settings for code signing. But I haven't been able to verify with `carthage build --no-skip-current`, but `xcodebuild`works fine. I'll try to push now.

**Comment by duemunk** [comment]
Does 1.6.4 solve the issue? @ksmandersen

**Comment by ksmandersen** [comment]
Yes, it's solved now. Thanks! :+1:

**Comment by duemunk** [comment]
Awesome!
