### ISSUE TITLE
qos_class_t error

### ISSUE THREAD

**Issue by shanmarkus** [duemunk/Async#66]
Pods/Async/Source/Async.swift:280:24: Redundant conformance of 'qos_class_t' to protocol 'Equatable'

![screen shot 2015-11-09 at 5 08 06 pm](https://cloud.githubusercontent.com/assets/3590755/11031072/959e7034-8704-11e5-81a0-be851235b7d1.png)

**Comment by duemunk** [comment]
It seems like you're on an old version of Async? This line has been remove since what it did became built in to Swift 2.1.

**Comment by shanmarkus** [comment]
Thank you so much ! i just remembered i was using this https://github.com/duemunk/Async/issues/60
