### ISSUE TITLE
Cannot load underlying module for 'Async'

### ISSUE THREAD

**Issue by donnay** [duemunk/Async#68]
installed the pod and when 'Import Async' in the main via controller got this error.
Cannot load underlying module for 'Async'

can build and run the 'AsyncExample iOS' w/o error

total noob here, any advice is appreciated

**Comment by duemunk** [comment]
What version of CocoaPods + Xcode are you using? And what does your podfile look like?

**Comment by donnay** [comment]
Thanks for the quick response Tobias,

I am using Xcode Version 7.1.1 (7B1005), and the latest AsyncSwift CocoaPod my pod file looks like this:

platform :ios, '8.0'
use_frameworks!
 
target 'mBibe' do
  pod 'SVProgressHUD', '~> 1.1'
  pod 'PermissionScope', '~> 1.0'
  pod 'SwiftLocation', '~> 0.2.0'
  pod 'PromiseKit', '~> 3.0.0'
  pod 'EVCloudKitDao'
  pod 'AsyncSwift'
  
end

**Comment by duemunk** [comment]
Are you also using the latest version of CocoaPods?

**Comment by donnay** [comment]
I just Un-installed / installed and now I'm using cocoapods-0.39.0
Now I can import Async

Thank you!
