### ISSUE TITLE
High CPU usage on background threads after a couple of seconds

### ISSUE THREAD

**Issue by DrewKiino** [duemunk/Async#73]
I have this code and similar code like it around my app.

```swift
    Async.background { [weak listing] in
      
      var coloredString: NSMutableAttributedString? = NSMutableAttributedString(string: "Price: $\(listing?.price ?? "")")
      coloredString?.addAttribute(NSForegroundColorAttributeName, value: UIColor.blackColor(), range: NSRange(location: 0,length: 6))
      coloredString?.addAttribute(NSFontAttributeName, value: UIFont.asapRegular(12), range: NSRange(location: 0,length: 6))
      
      Async.main { [weak self] in
        
        self?.bookPriceLabel?.attributedText = coloredString
        
        coloredString = nil
      }
    }
```

when I profile the CPU on xcode, the app opens up around 11 threads showing cpu usage  for the first few seconds, this is expected since the app runs all the code for setup. however, after a couple of seconds after, the threads that were used by the library spike in CPU usage and steadily increase till my computer reaches 100%. Not sure why!

**Comment by duemunk** [comment]
Since **Async** is only a wrapper for GCD, you might want to just do the `dispatch_async`-dance and see if the issue persists. If it doesn't, get back here, else give the time profiler another run.
