### ISSUE TITLE
Allow initializer access?

### ISSUE THREAD

**Issue by efremidze** [duemunk/Async#76]
Currently i'm trying to add an extension but I can't since I can't initialize the struct. `Async(block)`
```
static func safeMain(block: dispatch_block_t) -> Async {
    if NSThread.isMainThread() {
        block()
        return Async(block)
    }
    return main(block: block)
}
```
Related to #67

**Comment by duemunk** [comment]
I dont' think exposing the struct is the solution. Try and make a pull request that integrates this into Async instead. 

Also, I personally don't see value in this at all though. If an API don't document whether they return on same thread or on main, you should have that fixed instead. Enlighten me :)

**Comment by efremidze** [comment]
Your right, this shouldn't be added to the library. This is an edge case.
