### ISSUE TITLE
Support for dispatch_group

### ISSUE THREAD

**Issue by duemunk** [duemunk/Async#8]
Wait for multiple blocks to finish
```swift
let block1 = Async.utility {}
let block2 = Async.background {}
Async.main(when: block1, block2) {}
```
using [dispatch_group()](https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html)

**Comment by harlanhaskins** [comment]
Sorry to reopen an old discussion, but I'd love this in Async. I've only got one thing in my app using `dispatch_group`, but it'd be much simpler to be able to do them with Async.

**Comment by duemunk** [comment]
@harlanhaskins Please feel free to extend Async to support `dispatch_group`s. I haven't had the use of groups myself, so I think it would be better for you to make a suggestion.

**Comment by eneko** [comment]
I've gone on a different direction and added AsyncGroup (see [#75](https://github.com/duemunk/Async/pull/75)).  It does not support chaining, which I thought would be confusing with group blocks. It also has support for arbitrary non-GCD blocks.

**Comment by duemunk** [comment]
Thanks @eneko! I think this simplified approach is better, and at least good for now. Hopefully Swift gets better asynchronous support by version 4.0 or 5.0 :)
