### ISSUE TITLE
Why groups need to block current thread?

### ISSUE THREAD

**Issue by Gentlee** [duemunk/Async#84]
Why not to make non-blocking group.onComplete(callback: () -> Void) or smth?
And also group.onComplete(callback: (results: [AnyObject?]) -> Void) with array that contains results of operations?

**Comment by duemunk** [comment]
Hi @Gentlee 

Passing results between blocks, this has been discussed here https://github.com/duemunk/Async/issues/3.

Does this thread answer your question? If not, feel free to reopen this issue.

**Comment by Gentlee** [comment]
Hi @duemunk 

No it doesn't, main question was about blocking current thread on group.wait(). Blocking threads is a very bad thing, should be done only in console apps in main method not to finish the process.

**Comment by duemunk** [comment]
The `.wait()` way of doing it is very similar to how GCD handles it today.

You can see more on this in #82.

**Comment by Gentlee** [comment]
Man, do you understand why it is bad and why method wait shouldn't exists in app with UI?

**Comment by duemunk** [comment]
Correct me if I'm wrong, but `wait()` only blocks the thread it's called on, right? So just call it on any other thread than main.

Also, Async is not a UI framework or meant to be only used with that. Just sugar around GCD plus a few other conveniences.

**Comment by Gentlee** [comment]
@duemunk i see you are not much experienced yet in [multithread] programming. The main thing about it is that you should never block any thread. And about programming generally - you shouldn't force programmer to write more code than needed (more threads/blocks here). And you make these two mistakes here.

Also, now i understand - you just can't implement this method. If i have time i'll make pull request.

**Comment by josephlord** [comment]
@Gentlee That is complete rubbish. There are many situations where it is appropriate to block a queue (and sometimes even a thread). Your comment was rude and inappropriate too.

**Comment by ksmandersen** [comment]
@Gentlee There is no need to be condescending. I agree with @josephlord. There are lots of cases where you will need to wait on a thread.

Async is not a framework or suggestion on how to perform multithreaded programming. Just wrappers around pre-existing C function calls.
